/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package KeyWord;

import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.stream.Collectors;

/**
 *
 * @author Саня
 */
public class KeyWordsTable extends javax.swing.JFrame {

    Map<String, Integer> keyWords;
    
    /**
     * Creates new form KeyWordsTable
     * @param keyWords
     */
    public KeyWordsTable(Map<String, Integer> keyWords) {
        this.keyWords = new HashMap<>(keyWords);
        this.keyWords = sortByValue(this.keyWords);
        
        System.out.println(this.keyWords);
        System.out.println(this.keyWords.size());
        initComponents();
    }
    
    private String[][] setTableElements(){
        int row = 1;
        int wordsCounter = 0;
        int repetationsCounter = 0;
        
        String[][] temp = new String[10][3];
        if(keyWords.size() < 10)
            temp = new String[keyWords.size()][3];
        for(int i=0; i<temp.length; i++){
            if(i >= 10)break;
            for(int j=0; j<temp[i].length; j++){
                if(j == 0){
                    temp[i][j] = String.valueOf(row);
                    row ++;
                }if(j == 1){
                    temp[i][j] = getWords()[wordsCounter];
                    wordsCounter ++;
                }if(j == 2){
                    temp[i][j] = getRepetations()[repetationsCounter];
                    repetationsCounter ++;
                }
            }
        }
        return temp;
    }
    
    private String[] getWords(){
        String [] words = new String[keyWords.size()];
        int counter = 0;
        for(String word: keyWords.keySet()){
            words[counter] = word;
            counter ++;
        }
        //Arrays.sort(words, Collections.reverseOrder());
        return words;
    }
    
    public static <K, V extends Comparable<? super V>> Map<K, V> sortByValue(Map<K, V> map) {
    return map.entrySet()
              .stream()
              .sorted(Map.Entry.comparingByValue(Collections.reverseOrder()))
              .collect(Collectors.toMap(
                Map.Entry::getKey, 
                Map.Entry::getValue, 
                (e1, e2) -> e1, 
                LinkedHashMap::new
              ));
    }
    
    private String[] getRepetations(){
        String [] repatations = new String[keyWords.size()];
        int counter = 0;
        for(int rep: keyWords.values()){
            repatations[counter] = String.valueOf(rep);
            counter ++;
        }
        //Arrays.sort(repatations);
        return repatations;
    }
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            setTableElements(),
            new String [] {
                "№", "Cлова", "Повторы"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
